"""add user_details table

Revision ID: c543abe9c535
Revises: 377309bfcf76
Create Date: 2026-05-23 19:47:44.553698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c543abe9c535'
down_revision: Union[str, None] = '377309bfcf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('F', 'M', name='genenum'), nullable=True),
    sa.Column('waist', sa.Integer(), nullable=True),
    sa.Column('hip', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'slightly_active', 'moderate', 'highly_active', 'extremely_active', name='activitylevelenum'), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('mzt', sa.Float(), nullable=True),
    sa.Column('ts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    # ### end Alembic commands ###
